#spring:
#  application:
#    name: demo
#
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  mail:
#    host: smtp.naver.com
#    port: 587
#    protocol: smtp
#    smtp:
#      auth: true
#      ssl:
#        enable: true
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    default-encoding: UTF-8
#    pop3:
#      host: pop.naver.com
#      port: 995
#      ssl:
#        enable: true
#
#jwt:
#  secret: ${JWT_SECRET}
#  expiration-period: ${JWT_EXPIRATION}
