version: "3.8"

services:
  app:
    image: ${DOCKERHUB_USERNAME}/furniture:latest
    container_name: backend-server
    ports:
      - 8080:8080
    volumes:
      - ./application.properties:/app/config/application.properties
    command: ["java", "-jar", "app.jar", "--spring.config.location=file:/app/config/application.properties"]
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
